server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: tuxpoli
    password: tuxpoli
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: orlye.ac@gmail.com
    password: confidential
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    customer-created: internal.customer-created.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
