name: api ci workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: find name
        id: findname
        run: echo "$(docker ps | grep postgres | awk '{print $1}')"
      - name: adding customer database
        run: docker exec $(docker ps | grep postgres | awk '{print $1}') psql -U tuxpoli -W tuxpoli -c 'CREATE DATABASE customer;'
      - name: adding notification database
        run: docker exec $(docker ps | grep postgres | awk '{print $1}') psql -U tuxpoli -W tuxpoli -c 'CREATE DATABASE notification;'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify
