name: api ci workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build-customer-domain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./customer/domain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-customer-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./customer/application
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-customer-infrastructure:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./customer/infrastructure
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-customer-microservice-entry:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./customer/microservice-entry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-notification-domain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notification/domain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-notification-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notification/application
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-notification-infrastructure:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./notification/infrastructure
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify

  build-notification-microservice-entry:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./notification/microservice-entry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: unit and integration tests if compiled
        run: mvn -ntp -B verify
