name: api deploy workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: tuxpoli
          POSTGRES_PASSWORD: tuxpoli
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: login to docker hub to push image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: find name
        id: findname
        run: read -d ' ' THE_INITIAL_NAME <<< $(docker ps | grep postgres) && echo "THE_NAME=${THE_INITIAL_NAME}" >> $GITHUB_OUTPUT
      - name: adding customer database
        run: docker exec ${{steps.findname.output.THE_NAME}} psql -U tuxpoli -W tuxpoli -c 'CREATE DATABASE customer;'
      - name: adding notification database
        run: docker exec ${{steps.findname.output.THE_NAME}} psql -U tuxpoli -W tuxpoli -c 'CREATE DATABASE notification;'
      - name: making id to compile
        id: idcompile
        run: echo "BUILD_NUMBER=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: maven package compile and push image
        run: mvn -ntp -B -P jibbuild verify -Ddocker.image.tag=${{steps.idcompile.outputs.BUILD_NUMBER}}
